services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432